--- 
components: 
  schemas:
    WaterPotabilityMetrics:
      description: 'Water potability data model is intended to represent water quality parameters at a certain water mass (river,  lake, sea, etc.) section. For the puspose of indicating if water is safe for human consumption'
      properties:
        pH:
            description: 'Acidity or basicity of an aqueous solution. WHO has recommended maximum permissible limit of pH from 6.5 to 8.5.'
            maximum: 8.5
            minimum: 6.5
            type: number
        Hardness:
          description: 'The amount of dissolved calcium and magnesium in the water.'
          minimum: 0
          type: number
        Solids:
          description: 'Total dissolved solids. Desirable limit for TDS is 500 mg/l and maximum limit is 1000 mg/l which prescribed for drinking purpose. '
          minimum: 500
          maximum: 1000
          x-ngsi:
            units: mg/l
          type: number
          
        Chloramines:
          description: 'Disinfectants used to treat drinking water. Chlorine levels up to 4 milligrams per liter (mg/L or 4 parts per million (ppm)) are considered safe in drinking water.'
          maximum: 4
          x-ngsi:
            units: mg/l
          type: number
        Sulfate:
          description: 'Concentration of sulfate. Sulfate concentration in seawater is about 2,700 milligrams per liter (mg/L). It ranges from 3 to 30 mg/L in most freshwater supplies, although much higher concentrations (1000 mg/L) are found in some geographic locations.'
          minimum: 3
          x-ngsi:
            units: mg/l
          type: number
        Conductivity:
          description: 'Electrical Conductivity. According to WHO standards, EC value should not exceeded 400 μS/cm.'
          maximum: 400
          x-ngsi:
            units: μS/cm
          type: number
        Organic_carbon:
          description: 'Measure of the total amount of carbon in organic compounds in pure water. According to US EPA < 2 mg/L as TOC in treated / drinking water, and < 4 mg/Lit in source water which is use for treatment.'
          type: number
        Trihalomethanes:
          description: 'THMs are chemicals which may be found in water treated with chlorine. THM levels up to 80 ppm is considered safe in drinking water.'
          type: number
          maximum: 80
          x-ngsi:
            units: ppm
        Turbidity:
          description: 'Amount of light scattered by particles in the water column. The mean turbidity value obtained for Wondo Genet Campus (0.98 NTU) is lower than the WHO recommended value of 5.00 NTU.'
          type: number
        Potability:
          description: 'Indicates if water is safe for human consumption where 1 means Potable and 0 means Not potable.'
          minimum: 0
          maximum: 1
          type: number


info: 
  description: "Base Model Definitions from Smart Data Models"
  title: Water potabilty data model
  version: "1.0.0"
openapi: "3.0.0"


# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      responses: 
        ? "200"
        : 
          description:  OK
          content: 
            application/ld+json: 
              schema: 
                type: object